### PR TITLE
added optional mission description

### PR DESCRIPTION
**Pull request by edewit**
part of https://github.com/fabric8-launcher/launcher-planning/issues/74

### CODE REVIEW

**Comment by gastaldi** [comment]
I'll let @quintesse handle this since he is working on the Booster.yaml improvements

**Comment by quintesse** [comment]
I'll merge this. Btw, shouldn't `Runtime` have this as well @edewit ?

**Comment by edewit** [comment]
currently runtimes only have icons

**Comment by quintesse** [comment]
Sure, but look at the new UI design: https://redhat.invisionapp.com/share/VGF1RF15J#/screens/269596449 , I think we'll need that description at some point.

**Pull request merged**
